version: '3.3'

services:
  postgres:
    container_name: mi_linda_db
    image: postgres:13
    environment:
      - POSTGRES_DB=my_tiendita
      - POSTGRES_USER=may
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres
